### ISSUE TITLE
Wrong start and end line numbers for CPP elements

### ISSUE THREAD

**Issue by ckroeher** [KernelHaven/srcMLExtractor#10]
When calling the methods `getLineStart()` and/or `getLineEnd()` on objects of type `CppBlock` or `CppStatement`, the return value is always *-1* instead of the line numbers marking the start and end of the respective block or statement in their parent code file.

For example, extracting the following code file:
```c
#include <stdio.h>

int main(int argc, char **argv) {
#ifdef CONFIG_DEBUG
    printf("Debugging");
#endif
    return 0;
}
```
should provide a `CppBlock` object, where calling the methods should return the following numbers:
- `getLineStart()` = 4
- `getLineEnd()` = 6

**Comment by adam-sse** [comment]
Fixed in 91cc8b27d71c258fe60e4abaa5fc7e9556b8bf88.

Btw, the end line number is 5, not 6.
